In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv ('Salary_Data.csv')
data

    YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081
14              4.5  25.0   61111
15              4.9  25.0   67938
16              5.1  26.0   66029
17              5.3  27.0   83088
18              5.9  28.0   81363
19              6.0  29.0   93940
20              6.8  30.0   91738
21              7.1  30.0   98273
22              7.9  31.0  101302
23              8.2  32.0  113812
24              8.7  33.0  109431
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [ ]:
data.head()

   YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891

In [ ]:
mean_age = data['Age'].mean()
mean_age

27.216666666666665

In [ ]:
median_age = data['Age'].median()
median_age

25.0

In [ ]:
std_age = data['Age'].std()
std_age

5.161267108077196

In [ ]:
#TASK 2

In [ ]:
data = pd.read_csv ('Salary_Data.csv')
data

    YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081

In [ ]:
data1 = pd.read_csv ('Salary_Data2.csv')
data

    YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081

In [ ]:
data = [pd.read_csv('Salary_Data.csv'), pd.read_csv('Salary_Data2.csv')]
array = pd.concat(data)
array

    YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081
0               4.5  25.0   61111
1               4.5  25.0   67938
2               4.5  26.0   66029
3               4.5  27.0   83088
4               4.5  28.0   81363
5               4.5  29.0   93940
6               4.5  30.0   91738
7               4.5  30.0   98273
8               4.5  31.0  101302
9               4.5  32.0  113812
10              4.5  33.0  109431
11              4.5  34.0  105582
12              4.5  35.0  116969
13              4.5  36.0  112635
14              4.5  37.0  122391
15              4.5  38.0  121872

In [ ]:
#Task 3

In [ ]:
data = pd.read_excel('bigdata.xls')
data

,Unnamed: 0,First Name,Last Name,Gender,Country,Age,Date,Id
0,1,Dulce,Abril,Female,United States,32,15/10/2017,1562
1,2,Mara,Hashimoto,Female,Great Britain,25,16/08/2016,1582
2,3,Philip,Gent,Male,France,36,21/05/2015,2587
3,4,Kathleen,Hanner,Female,United States,25,15/10/2017,3549
4,5,Nereida,Magwood,Female,United States,58,16/08/2016,2468
...,...,...,...,...,...,...,...,...
995,996,Roma,Lafollette,Female,United States,34,15/10/2017,2654
996,997,Felisa,Cail,Female,United States,28,16/08/2016,6525
997,998,Demetria,Abbey,Female,United States,32,21/05/2015,3265
998,999,Jeromy,Danz,Male,United States,39,15/10/2017,3265
999,1000,Rasheeda,Alkire,Female,United States,29,16/08/2016,6125

In [ ]:
data.describe()

        Unnamed: 0          Age           Id
count  1000.000000  1000.000000  1000.000000
mean    500.500000    33.260000  4717.720000
std     288.819436     8.353573  2368.340592
min       1.000000    21.000000  1258.000000
25%     250.750000    26.000000  2587.000000
50%     500.500000    32.000000  3574.000000
75%     750.250000    38.000000  6540.000000
max    1000.000000    58.000000  9654.000000

In [ ]:
data1 = data.groupby(['Country','Age']).sum()
data1

                   Unnamed: 0      Id
Country       Age
France        21        10000  131480
              23        10060  108240
              24        20180   96100
              26         9880  193080
              27        10240  172840
              35        10180  151380
              36         9560   51740
              38         9740   51580
              39         9840   71580
              42         9980  109780
              46         9900   71380
Great Britain 25         9540   31640
              26        19940  180900
              28        39680  418040
              31         9800   65180
              32         9760   65120
              34        10140  150420
              37        10120   91380
              39         9720   25160
              46         9960  109780
              56         9640   71960
United States 24         9620   51080
              25        19840  261700
              26        20720  196100
              27         9660   49120
              28        10440  130500
              29        30760  416260
              32        19980   96540
              34        10420   53080
              36        20480  221620
              37        30560  269660
              39        20860  136640
              40         9680  130960
              41        10080   65120
              52         9940  171220
              58         9600   49360

In [ ]:
mean_age = data['Age'].mean()
mean_age

33.26

In [ ]:
median_age = data['Age'].median()
median_age

32.0

In [ ]:
std_age = data['Age'].std()
std_age

8.353573018905275

In [ ]:
sum = data['Age'].sum()
sum

33260